#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2
# #+BEAMER_THEME: Madrid
#+COLUMNS: %45ITEM %10BEAMER_ENV(Env) %10BEAMER_ACT(Act) %4BEAMER_COL(Col) %8BEAMER_OPT(Opt)
     
#+LaTex_HEADER: \usepackage{khpreamble, euscript}
#+LaTex_HEADER: \DeclareMathOperator{\atantwo}{atan2}
#+LaTex_HEADER: \newcommand*{\ctrb}{\EuScript{C}}
#+LaTex_HEADER: \newcommand*{\obsv}{\EuScript{O}}

#+title:  Robot móvil tipo uniciclo
# #+date: 2018-04-05

* What do I want the students to understand?			   :noexport:
- The dynamics of the unicycle model

* Activities                                                       :noexport:
- Program function that takes linear and angular velocity in SI measurements as input  and
  computes the velocity of each wheel.
- Implement open-loop control to move roverbot in square.
  

* Mobile robot unicycle model

** Robot móvil  
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

    \begin{center}
     \includegraphics[width=.8\linewidth]{../figures/X80Pro.jpg}
    \end{center}




*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../figures/unicycle_annotated.png}
    \end{center}

** Robot móvil - modelo uniciclo
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

    \begin{center}
     \includegraphics[width=.3\linewidth]{../figures/X80Pro.jpg}
    \end{center}
    \begin{center}
     \includegraphics[width=1.0\linewidth]{../figures/unicycle-model}
    \end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

#+BEAMER: \pause

*Cinemática*

    \[ \xi = \begin{bmatrix} \theta\\x\\y \end{bmatrix},   \quad u = \begin{bmatrix} \omega\\v \end{bmatrix}\]



    \[\frac{d}{dt} \xi = \begin{bmatrix} \dot{\theta}\\\dot{x}\\\dot{y} \end{bmatrix} = \begin{bmatrix} \omega\\ v\cos\theta\\v\sin\theta\end{bmatrix} \]

    
#+BEAMER: \pause

*Actividad* En simulink

*** Notes                                                          :noexport:
- Add three integrators, label
- Add XY-scope and regular scope
- Link x and y to XY-scope, link theta to other scope
- Add two sources for the control inputs \omega and v.
- Leave the rest to the students.
- Goal: Make robot move in circular of radius 2m, finishing the revolution in 10s
  - Angular vel: \omega = 2*pi/10
  - Linear vel: 2*pi*r/10



** Diferencial a modelo uniciclo
*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../figures/unicycle-model-details}
    \end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:


*Cinemática*

#+BEAMER: \pause

*Actividad* Determine

1) La velocidad lineal ($v_R$, $v_L$) de cada rueda dado su velocidad angular ($\omega_R$, $\omega_L$)

2) La velocidad lineal $v$ del centro robot dado las dos velocidades $v_R$ y $v_L$

3) La velocidad angular $\omega$ del robot dado las dos velocidades $v_R$ y $v_L$

4) Las relaciones invertidas. Es decir, las velocidades angulares $\omega_R$ y $\omega_L$ de los ruedos dado las velocidades $v$ y $\omega$.

   
** Implementación de la cinemática inversa

En simulink/matlab


* Control en lazo abierto

** Control en lazo abierto

*** Graphics
:PROPERTIES:
:BEAMER_col: 0.4
:END:

    \begin{center}
     \includegraphics[width=1.0\linewidth]{../figures/unicycle-model}
    \end{center}

*** Text
:PROPERTIES:
:BEAMER_col: 0.6
:END:

#+BEAMER: \pause

Queremos manejar el robot de un estado inicial a otro estando. Es decir eligir una señal de entrada
$$ u(t) = \begin{bmatrix} v(t)\\\omega_t \end{bmatrix}, \; t \in [0,\, t_1) $$
que mueve el robot de una posición y orientación inicial ($x(0)$, $y(0)$, $\theta(0)$) a otra posición y orientación en $t_1$ segundos.

#+BEAMER: \pause

*Actividad*

Dibuje la señal de entrada que 
1) mueve el robot una distancia 1m derecho en 3 segundos.
2) cambia la dirección del robot 90 grados hacia izquierda.
3) que mueve el robot en una trayectoria de forma cuadrada con lados de 1 metros en 20 segundos.

** Implementación del control en lazo abierto

Simulink









